MediaBrowser/plugin.video.emby

resources/lib/UserClient.py, resources/lib/Utils.py, resources/lib/WriteKodiMusicDB.py, resources/settings.xml, service.py
make it seemless - dependant on alternate ip to be enabled to add
pathsubstitution.
=> Music library

resources/lib/read_embyserver.py
Ooops!   My bad.  Replaced in wrong file.
=> Invalid path

resources/lib/utils.py, resources/lib/videonodes.py
Use the c module if avail (built in 2.5+)
=> Faster XML processing and lower memory

resources/lib/utils.py, resources/lib/videonodes.py
Reverts MediaBrowser/plugin.video.emby#44
This commit causes library sync thread error on libreelec see:http://sprunge.us/dJcG
Reverting fixed it...but probably needs some investigation as to why its causing it
=> Revert "Faster XML processing and lower memory"

resources/lib/artwork.py, resources/lib/connect/connectionmanager.py, resources/lib/connectmanager.py, resources/lib/downloadutils.py, resources/lib/entrypoint.py, resources/lib/kodimonitor.py, resources/lib/librarysync.py, resources/lib/service_entry.py, resources/lib/userclient.py, resources/lib/websocket_client.py
Support downloading information from multiple servers
=> Rework downloadutils

resources/lib/utils.py, resources/lib/videonodes.py
=> Nest emby video nodes logically

resources/language/Czech/strings.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mediabrowser/plugin.video.emby/81)
=> Add Czech Language

resources/lib/kodimonitor.py
If kodi_id is not supplied then retrieve the kodi_id of the current file from the kodi database
=> get kodi_id from kodi database

resources/lib/objects/tvshows.py
Sometimes it's better to take a break to find the SMALL problem ;)
This will solve the problem with episode metadata updates of Emby<->Kodi.
=> Fixed wrong episode uniqueids in the UNIQUEID and RATING table.

resources/lib/objects/_kodi_movies.py, resources/lib/objects/_kodi_tvshows.py, resources/lib/objects/movies.py, resources/lib/objects/tvshows.py
See: https://emby.media/community/index.php?/topic/48414-issue-with-updating-ratings-for-movies/
This will solve the issue that wrong uniqueIDs will be fetched.
=> Fixed uniqueID and ratingID issues

resources/lib/downloadutils.py, resources/lib/websocket_client.py
Add SetRepeatMode feature for remote control
=> Add SetRepeatMode feature

resources/lib/database.py, resources/lib/playutils.py
Get codec information from database instead of filename
Allow transcoding of 10bit HEVC using existing High10P setting
Added case for non-default video track ids
Update Leia Video DB
=> Improve transcoding detection

resources/lib/websocket.py
The current implementation of the websocket module does not support SNI for SSL sockets.
I noticed that my sync stopped working (only library scan on startup worked fine, but no "live" syncs) when I moved my emby server behind cloudflare including their SSL. Accessing this without SNI enabled clients is not working. The emby plugin throws an "SSLV3_ALERT_HANDSHAKE_FAILURE" error, if debug log level is enabled.
This pull request backports the necessary SNI part from the upstream websocket implementation.
Thanks for considering this.
=> Add SNI support for SSL socket

resources/lib/database/__init__.py
=> Fix database discovery

resources/lib/database/__init__.py, resources/lib/entrypoint/service.py, resources/lib/library.py, resources/settings.xml
Update database discovery
Ensure widgets get updated
=> Update database discovery

objects/actions.py
switched to xbmc.PlayList() function and removed unnecessary xbmc.sleep and leftovers from the special listener
=> cleanup actions.py

addon.xml, context.py
=> Version bump 4.0.3

resources/lib/webservice.py
=> speed up playback

objects/movies.py
Use real path for local trailers with native playback mode
=> Movie trailers

resources/lib/library.py
This PR is a suggestion for fixing issue #305 that was opened by me some time ago.
I've tested it on some of my Kodi installations and it seems that now my Emby server is not running into memory issues.
The plugin also doesn't fail with a timeout error anymore.
For achieving that I used the already implemented `get_items` method of `resources/lib/downloader.py`. As additional query parameter I used `MinDateLastSavedForUser`. This parameter is also used in the previous used method `get_date_modified` of `libraries/emby/core/api.py`.
When using the `get_items` method as described above, only chunks with the size of the `limitIndex` setting of the plugin are fetched from the Emby server.
In my second commit I added some progress output for the user. This is usefull if there are a lot of …
=> Suggestion for issue #305

libraries/emby/core/http.py
Please have a look on the above issue #308 and the following thread for more information: https://emby.media/community/index.php?/topic/78585-emby-libraries-not-syncing-to-kodi/
=> Temporary fix for issue #308

addon.xml, libraries/emby/core/connection_manager.py, resources/language/resource.language.en_gb/strings.po, resources/lib/library.py, resources/lib/views.py
=> 4.1.15 part 2

addon.xml, core/movies.py, core/music.py, core/musicvideos.py, core/queries_music.py, core/tvshows.py, database/database.py, database/library.py, database/sync.py, emby/core/api.py, helper/pluginmenu.py, hooks/monitor.py, hooks/player.py, service.py
plugin.video.emby-next-gen-5.3.3-build 19 (ex1)
=> plugin.video.emby-next-gen-5.3.3-build 19 (ex1)

addon.xml, changelog.txt, core/common.py, database/library.py, helper/xmls.py
- fix remove item issue
- fix recording issue
- fix native season path
=> plugin.video.emby-next-gen-6.0.11-build 5 (ex2)

addon.xml, core/movies.py, database/library.py, hooks/websocket.py
=> plugin.video.emby-next-gen-6.0.12-build 3 (ex1)

addon.xml, changelog.txt, emby/api.py
=> plugin.video.emby-next-gen-6.0.13-build 2 (ex1)

addon.xml, core/common.py, core/musicvideos.py, database/db_open.py, service.py
plugin.video.emby-next-gen-6.1.1-build 4 (ex1)
=> plugin.video.emby-next-gen-6.1.1-build 4 (ex1)

addon.xml, changelog.txt, database/library.py
=> plugin.video.emby-next-gen-6.1.8-build 1 (ex1)

addon.xml, changelog.txt, emby/api.py, helper/pluginmenu.py, hooks/monitor.py, hooks/player.py
fix delete option after playback
fix next episode node issue
backport 7.x progress update functions
=> next-gen v 6.2.16

addon.xml, changelog.txt, emby/views.py
Special charecter issue for Kodi 18
=> Special charecter issue for Kodi 18
